#include <iostream>
#include "bigint.h"
#include <chrono>

#include <iostream>
#include <fstream>
#include <array>
#include <string>
#include <vector>
#include <algorithm>
#include <time.h>

std::vector<int> check(int a, std::vector<int> b)
{
    std::vector<int> numbers;
    for(auto i : b)
    {
        if(i == a)
        {
            //std::cout << a << "\n";
            int temp = a % 100 * 100 + 10;
            if(temp > 1000)
            {
                for(int c = temp; c < temp + 90; c++)
                {
                    numbers.push_back(c);
                }
            }
        }
    }
    return numbers;
}

bool checkAll(int i, std::vector<int> a, std::vector<int> b, std::vector<int> c, std::vector<int> d, std::vector<int> e, std::vector<int> f)
{
    std::vector<int> one = check(i, a);
    for(auto j : one)
    {
        std::vector<int> two = check(j, b);
        for(auto k : two)
        {
            std::vector<int> three = check(k, c);
            for(auto l : three)
            {
                std::vector<int> four = check(l, d);
                for(auto m : four)
                {
                    std::vector<int> five = check(m, e);
                    for(auto n : five)
                    {
                        std::vector<int> six = check(n, f);
                        for(auto o : six)
                        {
                            if(o == i)
                            {
                                std::cout << "\n" << i << " : " << j << " : " << k << " : " << l << " : " << m << " : " << n << " : " << o;
                                return true;
                            }
                        }
                    }
                }
            }
        }
    }
    return false;
}


int main()
{
    std::vector<int> a, b, c, d, e, f;
    int temp = 0;
    int result = 0;
    while(result < 10000)
    {
        temp++;
        result = temp * (temp + 1) / 2;
        a.push_back(result);
    }
    result = 0;
    temp = 0;
    while(result < 10000)
    {
        temp++;
        result = temp * temp;
        b.push_back(result);
    }
    temp = 0;
    result = 0;
    while(result < 10000)
    {
        temp++;
        result = temp * (3 * temp - 1) / 2;
        c.push_back(result);
    }
    temp = 0;
    result = 0;
    while(result < 10000)
    {
        temp++;
        result = temp * (2 * temp - 1);
        d.push_back(result);
    }
    temp = 0;
    result = 0;
    while(result < 10000)
    {
        temp++;
        result = temp * (5 * temp - 3) / 2;
        e.push_back(result);
    }
    temp = 0;
    result = 0;
    while(result < 10000)
    {
        temp++;
        result = temp * (3 * temp - 2);
        f.push_back(result);
    }

    //    std::vector<char> chars = {'a','b','c','d','e','f'};
    //    do {
    //        std::cout << "checkAll(i, " << chars[0] << ", " << chars[1] << ", " <<
    //                     chars[2] << ", " << chars[3] << ", " <<
    //                     chars[4] << ", " << chars[5] << ");\n";
    //    } while(std::next_permutation(chars.begin(), chars.end()));

    for(int i = 1010; i < 9999; i++)
    {
        checkAll(i, a, b, c, d, e, f);
        checkAll(i, a, b, c, d, f, e);
        checkAll(i, a, b, c, e, d, f);
        checkAll(i, a, b, c, e, f, d);
        checkAll(i, a, b, c, f, d, e);
        checkAll(i, a, b, c, f, e, d);
        checkAll(i, a, b, d, c, e, f);
        checkAll(i, a, b, d, c, f, e);
        checkAll(i, a, b, d, e, c, f);
        checkAll(i, a, b, d, e, f, c);
        checkAll(i, a, b, d, f, c, e);
        checkAll(i, a, b, d, f, e, c);
        checkAll(i, a, b, e, c, d, f);
        checkAll(i, a, b, e, c, f, d);
        checkAll(i, a, b, e, d, c, f);
        checkAll(i, a, b, e, d, f, c);
        checkAll(i, a, b, e, f, c, d);
        checkAll(i, a, b, e, f, d, c);
        checkAll(i, a, b, f, c, d, e);
        checkAll(i, a, b, f, c, e, d);
        checkAll(i, a, b, f, d, c, e);
        checkAll(i, a, b, f, d, e, c);
        checkAll(i, a, b, f, e, c, d);
        checkAll(i, a, b, f, e, d, c);
        checkAll(i, a, c, b, d, e, f);
        checkAll(i, a, c, b, d, f, e);
        checkAll(i, a, c, b, e, d, f);
        checkAll(i, a, c, b, e, f, d);
        checkAll(i, a, c, b, f, d, e);
        checkAll(i, a, c, b, f, e, d);
        checkAll(i, a, c, d, b, e, f);
        checkAll(i, a, c, d, b, f, e);
        checkAll(i, a, c, d, e, b, f);
        checkAll(i, a, c, d, e, f, b);
        checkAll(i, a, c, d, f, b, e);
        checkAll(i, a, c, d, f, e, b);
        checkAll(i, a, c, e, b, d, f);
        checkAll(i, a, c, e, b, f, d);
        checkAll(i, a, c, e, d, b, f);
        checkAll(i, a, c, e, d, f, b);
        checkAll(i, a, c, e, f, b, d);
        checkAll(i, a, c, e, f, d, b);
        checkAll(i, a, c, f, b, d, e);
        checkAll(i, a, c, f, b, e, d);
        checkAll(i, a, c, f, d, b, e);
        checkAll(i, a, c, f, d, e, b);
        checkAll(i, a, c, f, e, b, d);
        checkAll(i, a, c, f, e, d, b);
        checkAll(i, a, d, b, c, e, f);
        checkAll(i, a, d, b, c, f, e);
        checkAll(i, a, d, b, e, c, f);
        checkAll(i, a, d, b, e, f, c);
        checkAll(i, a, d, b, f, c, e);
        checkAll(i, a, d, b, f, e, c);
        checkAll(i, a, d, c, b, e, f);
        checkAll(i, a, d, c, b, f, e);
        checkAll(i, a, d, c, e, b, f);
        checkAll(i, a, d, c, e, f, b);
        checkAll(i, a, d, c, f, b, e);
        checkAll(i, a, d, c, f, e, b);
        checkAll(i, a, d, e, b, c, f);
        checkAll(i, a, d, e, b, f, c);
        checkAll(i, a, d, e, c, b, f);
        checkAll(i, a, d, e, c, f, b);
        checkAll(i, a, d, e, f, b, c);
        checkAll(i, a, d, e, f, c, b);
        checkAll(i, a, d, f, b, c, e);
        checkAll(i, a, d, f, b, e, c);
        checkAll(i, a, d, f, c, b, e);
        checkAll(i, a, d, f, c, e, b);
        checkAll(i, a, d, f, e, b, c);
        checkAll(i, a, d, f, e, c, b);
        checkAll(i, a, e, b, c, d, f);
        checkAll(i, a, e, b, c, f, d);
        checkAll(i, a, e, b, d, c, f);
        checkAll(i, a, e, b, d, f, c);
        checkAll(i, a, e, b, f, c, d);
        checkAll(i, a, e, b, f, d, c);
        checkAll(i, a, e, c, b, d, f);
        checkAll(i, a, e, c, b, f, d);
        checkAll(i, a, e, c, d, b, f);
        checkAll(i, a, e, c, d, f, b);
        checkAll(i, a, e, c, f, b, d);
        checkAll(i, a, e, c, f, d, b);
        checkAll(i, a, e, d, b, c, f);
        checkAll(i, a, e, d, b, f, c);
        checkAll(i, a, e, d, c, b, f);
        checkAll(i, a, e, d, c, f, b);
        checkAll(i, a, e, d, f, b, c);
        checkAll(i, a, e, d, f, c, b);
        checkAll(i, a, e, f, b, c, d);
        checkAll(i, a, e, f, b, d, c);
        checkAll(i, a, e, f, c, b, d);
        checkAll(i, a, e, f, c, d, b);
        checkAll(i, a, e, f, d, b, c);
        checkAll(i, a, e, f, d, c, b);
        checkAll(i, a, f, b, c, d, e);
        checkAll(i, a, f, b, c, e, d);
        checkAll(i, a, f, b, d, c, e);
        checkAll(i, a, f, b, d, e, c);
        checkAll(i, a, f, b, e, c, d);
        checkAll(i, a, f, b, e, d, c);
        checkAll(i, a, f, c, b, d, e);
        checkAll(i, a, f, c, b, e, d);
        checkAll(i, a, f, c, d, b, e);
        checkAll(i, a, f, c, d, e, b);
        checkAll(i, a, f, c, e, b, d);
        checkAll(i, a, f, c, e, d, b);
        checkAll(i, a, f, d, b, c, e);
        checkAll(i, a, f, d, b, e, c);
        checkAll(i, a, f, d, c, b, e);
        checkAll(i, a, f, d, c, e, b);
        checkAll(i, a, f, d, e, b, c);
        checkAll(i, a, f, d, e, c, b);
        checkAll(i, a, f, e, b, c, d);
        checkAll(i, a, f, e, b, d, c);
        checkAll(i, a, f, e, c, b, d);
        checkAll(i, a, f, e, c, d, b);
        checkAll(i, a, f, e, d, b, c);
        checkAll(i, a, f, e, d, c, b);
        checkAll(i, b, a, c, d, e, f);
        checkAll(i, b, a, c, d, f, e);
        checkAll(i, b, a, c, e, d, f);
        checkAll(i, b, a, c, e, f, d);
        checkAll(i, b, a, c, f, d, e);
        checkAll(i, b, a, c, f, e, d);
        checkAll(i, b, a, d, c, e, f);
        checkAll(i, b, a, d, c, f, e);
        checkAll(i, b, a, d, e, c, f);
        checkAll(i, b, a, d, e, f, c);
        checkAll(i, b, a, d, f, c, e);
        checkAll(i, b, a, d, f, e, c);
        checkAll(i, b, a, e, c, d, f);
        checkAll(i, b, a, e, c, f, d);
        checkAll(i, b, a, e, d, c, f);
        checkAll(i, b, a, e, d, f, c);
        checkAll(i, b, a, e, f, c, d);
        checkAll(i, b, a, e, f, d, c);
        checkAll(i, b, a, f, c, d, e);
        checkAll(i, b, a, f, c, e, d);
        checkAll(i, b, a, f, d, c, e);
        checkAll(i, b, a, f, d, e, c);
        checkAll(i, b, a, f, e, c, d);
        checkAll(i, b, a, f, e, d, c);
        checkAll(i, b, c, a, d, e, f);
        checkAll(i, b, c, a, d, f, e);
        checkAll(i, b, c, a, e, d, f);
        checkAll(i, b, c, a, e, f, d);
        checkAll(i, b, c, a, f, d, e);
        checkAll(i, b, c, a, f, e, d);
        checkAll(i, b, c, d, a, e, f);
        checkAll(i, b, c, d, a, f, e);
        checkAll(i, b, c, d, e, a, f);
        checkAll(i, b, c, d, e, f, a);
        checkAll(i, b, c, d, f, a, e);
        checkAll(i, b, c, d, f, e, a);
        checkAll(i, b, c, e, a, d, f);
        checkAll(i, b, c, e, a, f, d);
        checkAll(i, b, c, e, d, a, f);
        checkAll(i, b, c, e, d, f, a);
        checkAll(i, b, c, e, f, a, d);
        checkAll(i, b, c, e, f, d, a);
        checkAll(i, b, c, f, a, d, e);
        checkAll(i, b, c, f, a, e, d);
        checkAll(i, b, c, f, d, a, e);
        checkAll(i, b, c, f, d, e, a);
        checkAll(i, b, c, f, e, a, d);
        checkAll(i, b, c, f, e, d, a);
        checkAll(i, b, d, a, c, e, f);
        checkAll(i, b, d, a, c, f, e);
        checkAll(i, b, d, a, e, c, f);
        checkAll(i, b, d, a, e, f, c);
        checkAll(i, b, d, a, f, c, e);
        checkAll(i, b, d, a, f, e, c);
        checkAll(i, b, d, c, a, e, f);
        checkAll(i, b, d, c, a, f, e);
        checkAll(i, b, d, c, e, a, f);
        checkAll(i, b, d, c, e, f, a);
        checkAll(i, b, d, c, f, a, e);
        checkAll(i, b, d, c, f, e, a);
        checkAll(i, b, d, e, a, c, f);
        checkAll(i, b, d, e, a, f, c);
        checkAll(i, b, d, e, c, a, f);
        checkAll(i, b, d, e, c, f, a);
        checkAll(i, b, d, e, f, a, c);
        checkAll(i, b, d, e, f, c, a);
        checkAll(i, b, d, f, a, c, e);
        checkAll(i, b, d, f, a, e, c);
        checkAll(i, b, d, f, c, a, e);
        checkAll(i, b, d, f, c, e, a);
        checkAll(i, b, d, f, e, a, c);
        checkAll(i, b, d, f, e, c, a);
        checkAll(i, b, e, a, c, d, f);
        checkAll(i, b, e, a, c, f, d);
        checkAll(i, b, e, a, d, c, f);
        checkAll(i, b, e, a, d, f, c);
        checkAll(i, b, e, a, f, c, d);
        checkAll(i, b, e, a, f, d, c);
        checkAll(i, b, e, c, a, d, f);
        checkAll(i, b, e, c, a, f, d);
        checkAll(i, b, e, c, d, a, f);
        checkAll(i, b, e, c, d, f, a);
        checkAll(i, b, e, c, f, a, d);
        checkAll(i, b, e, c, f, d, a);
        checkAll(i, b, e, d, a, c, f);
        checkAll(i, b, e, d, a, f, c);
        checkAll(i, b, e, d, c, a, f);
        checkAll(i, b, e, d, c, f, a);
        checkAll(i, b, e, d, f, a, c);
        checkAll(i, b, e, d, f, c, a);
        checkAll(i, b, e, f, a, c, d);
        checkAll(i, b, e, f, a, d, c);
        checkAll(i, b, e, f, c, a, d);
        checkAll(i, b, e, f, c, d, a);
        checkAll(i, b, e, f, d, a, c);
        checkAll(i, b, e, f, d, c, a);
        checkAll(i, b, f, a, c, d, e);
        checkAll(i, b, f, a, c, e, d);
        checkAll(i, b, f, a, d, c, e);
        checkAll(i, b, f, a, d, e, c);
        checkAll(i, b, f, a, e, c, d);
        checkAll(i, b, f, a, e, d, c);
        checkAll(i, b, f, c, a, d, e);
        checkAll(i, b, f, c, a, e, d);
        checkAll(i, b, f, c, d, a, e);
        checkAll(i, b, f, c, d, e, a);
        checkAll(i, b, f, c, e, a, d);
        checkAll(i, b, f, c, e, d, a);
        checkAll(i, b, f, d, a, c, e);
        checkAll(i, b, f, d, a, e, c);
        checkAll(i, b, f, d, c, a, e);
        checkAll(i, b, f, d, c, e, a);
        checkAll(i, b, f, d, e, a, c);
        checkAll(i, b, f, d, e, c, a);
        checkAll(i, b, f, e, a, c, d);
        checkAll(i, b, f, e, a, d, c);
        checkAll(i, b, f, e, c, a, d);
        checkAll(i, b, f, e, c, d, a);
        checkAll(i, b, f, e, d, a, c);
        checkAll(i, b, f, e, d, c, a);
        checkAll(i, c, a, b, d, e, f);
        checkAll(i, c, a, b, d, f, e);
        checkAll(i, c, a, b, e, d, f);
        checkAll(i, c, a, b, e, f, d);
        checkAll(i, c, a, b, f, d, e);
        checkAll(i, c, a, b, f, e, d);
        checkAll(i, c, a, d, b, e, f);
        checkAll(i, c, a, d, b, f, e);
        checkAll(i, c, a, d, e, b, f);
        checkAll(i, c, a, d, e, f, b);
        checkAll(i, c, a, d, f, b, e);
        checkAll(i, c, a, d, f, e, b);
        checkAll(i, c, a, e, b, d, f);
        checkAll(i, c, a, e, b, f, d);
        checkAll(i, c, a, e, d, b, f);
        checkAll(i, c, a, e, d, f, b);
        checkAll(i, c, a, e, f, b, d);
        checkAll(i, c, a, e, f, d, b);
        checkAll(i, c, a, f, b, d, e);
        checkAll(i, c, a, f, b, e, d);
        checkAll(i, c, a, f, d, b, e);
        checkAll(i, c, a, f, d, e, b);
        checkAll(i, c, a, f, e, b, d);
        checkAll(i, c, a, f, e, d, b);
        checkAll(i, c, b, a, d, e, f);
        checkAll(i, c, b, a, d, f, e);
        checkAll(i, c, b, a, e, d, f);
        checkAll(i, c, b, a, e, f, d);
        checkAll(i, c, b, a, f, d, e);
        checkAll(i, c, b, a, f, e, d);
        checkAll(i, c, b, d, a, e, f);
        checkAll(i, c, b, d, a, f, e);
        checkAll(i, c, b, d, e, a, f);
        checkAll(i, c, b, d, e, f, a);
        checkAll(i, c, b, d, f, a, e);
        checkAll(i, c, b, d, f, e, a);
        checkAll(i, c, b, e, a, d, f);
        checkAll(i, c, b, e, a, f, d);
        checkAll(i, c, b, e, d, a, f);
        checkAll(i, c, b, e, d, f, a);
        checkAll(i, c, b, e, f, a, d);
        checkAll(i, c, b, e, f, d, a);
        checkAll(i, c, b, f, a, d, e);
        checkAll(i, c, b, f, a, e, d);
        checkAll(i, c, b, f, d, a, e);
        checkAll(i, c, b, f, d, e, a);
        checkAll(i, c, b, f, e, a, d);
        checkAll(i, c, b, f, e, d, a);
        checkAll(i, c, d, a, b, e, f);
        checkAll(i, c, d, a, b, f, e);
        checkAll(i, c, d, a, e, b, f);
        checkAll(i, c, d, a, e, f, b);
        checkAll(i, c, d, a, f, b, e);
        checkAll(i, c, d, a, f, e, b);
        checkAll(i, c, d, b, a, e, f);
        checkAll(i, c, d, b, a, f, e);
        checkAll(i, c, d, b, e, a, f);
        checkAll(i, c, d, b, e, f, a);
        checkAll(i, c, d, b, f, a, e);
        checkAll(i, c, d, b, f, e, a);
        checkAll(i, c, d, e, a, b, f);
        checkAll(i, c, d, e, a, f, b);
        checkAll(i, c, d, e, b, a, f);
        checkAll(i, c, d, e, b, f, a);
        checkAll(i, c, d, e, f, a, b);
        checkAll(i, c, d, e, f, b, a);
        checkAll(i, c, d, f, a, b, e);
        checkAll(i, c, d, f, a, e, b);
        checkAll(i, c, d, f, b, a, e);
        checkAll(i, c, d, f, b, e, a);
        checkAll(i, c, d, f, e, a, b);
        checkAll(i, c, d, f, e, b, a);
        checkAll(i, c, e, a, b, d, f);
        checkAll(i, c, e, a, b, f, d);
        checkAll(i, c, e, a, d, b, f);
        checkAll(i, c, e, a, d, f, b);
        checkAll(i, c, e, a, f, b, d);
        checkAll(i, c, e, a, f, d, b);
        checkAll(i, c, e, b, a, d, f);
        checkAll(i, c, e, b, a, f, d);
        checkAll(i, c, e, b, d, a, f);
        checkAll(i, c, e, b, d, f, a);
        checkAll(i, c, e, b, f, a, d);
        checkAll(i, c, e, b, f, d, a);
        checkAll(i, c, e, d, a, b, f);
        checkAll(i, c, e, d, a, f, b);
        checkAll(i, c, e, d, b, a, f);
        checkAll(i, c, e, d, b, f, a);
        checkAll(i, c, e, d, f, a, b);
        checkAll(i, c, e, d, f, b, a);
        checkAll(i, c, e, f, a, b, d);
        checkAll(i, c, e, f, a, d, b);
        checkAll(i, c, e, f, b, a, d);
        checkAll(i, c, e, f, b, d, a);
        checkAll(i, c, e, f, d, a, b);
        checkAll(i, c, e, f, d, b, a);
        checkAll(i, c, f, a, b, d, e);
        checkAll(i, c, f, a, b, e, d);
        checkAll(i, c, f, a, d, b, e);
        checkAll(i, c, f, a, d, e, b);
        checkAll(i, c, f, a, e, b, d);
        checkAll(i, c, f, a, e, d, b);
        checkAll(i, c, f, b, a, d, e);
        checkAll(i, c, f, b, a, e, d);
        checkAll(i, c, f, b, d, a, e);
        checkAll(i, c, f, b, d, e, a);
        checkAll(i, c, f, b, e, a, d);
        checkAll(i, c, f, b, e, d, a);
        checkAll(i, c, f, d, a, b, e);
        checkAll(i, c, f, d, a, e, b);
        checkAll(i, c, f, d, b, a, e);
        checkAll(i, c, f, d, b, e, a);
        checkAll(i, c, f, d, e, a, b);
        checkAll(i, c, f, d, e, b, a);
        checkAll(i, c, f, e, a, b, d);
        checkAll(i, c, f, e, a, d, b);
        checkAll(i, c, f, e, b, a, d);
        checkAll(i, c, f, e, b, d, a);
        checkAll(i, c, f, e, d, a, b);
        checkAll(i, c, f, e, d, b, a);
        checkAll(i, d, a, b, c, e, f);
        checkAll(i, d, a, b, c, f, e);
        checkAll(i, d, a, b, e, c, f);
        checkAll(i, d, a, b, e, f, c);
        checkAll(i, d, a, b, f, c, e);
        checkAll(i, d, a, b, f, e, c);
        checkAll(i, d, a, c, b, e, f);
        checkAll(i, d, a, c, b, f, e);
        checkAll(i, d, a, c, e, b, f);
        checkAll(i, d, a, c, e, f, b);
        checkAll(i, d, a, c, f, b, e);
        checkAll(i, d, a, c, f, e, b);
        checkAll(i, d, a, e, b, c, f);
        checkAll(i, d, a, e, b, f, c);
        checkAll(i, d, a, e, c, b, f);
        checkAll(i, d, a, e, c, f, b);
        checkAll(i, d, a, e, f, b, c);
        checkAll(i, d, a, e, f, c, b);
        checkAll(i, d, a, f, b, c, e);
        checkAll(i, d, a, f, b, e, c);
        checkAll(i, d, a, f, c, b, e);
        checkAll(i, d, a, f, c, e, b);
        checkAll(i, d, a, f, e, b, c);
        checkAll(i, d, a, f, e, c, b);
        checkAll(i, d, b, a, c, e, f);
        checkAll(i, d, b, a, c, f, e);
        checkAll(i, d, b, a, e, c, f);
        checkAll(i, d, b, a, e, f, c);
        checkAll(i, d, b, a, f, c, e);
        checkAll(i, d, b, a, f, e, c);
        checkAll(i, d, b, c, a, e, f);
        checkAll(i, d, b, c, a, f, e);
        checkAll(i, d, b, c, e, a, f);
        checkAll(i, d, b, c, e, f, a);
        checkAll(i, d, b, c, f, a, e);
        checkAll(i, d, b, c, f, e, a);
        checkAll(i, d, b, e, a, c, f);
        checkAll(i, d, b, e, a, f, c);
        checkAll(i, d, b, e, c, a, f);
        checkAll(i, d, b, e, c, f, a);
        checkAll(i, d, b, e, f, a, c);
        checkAll(i, d, b, e, f, c, a);
        checkAll(i, d, b, f, a, c, e);
        checkAll(i, d, b, f, a, e, c);
        checkAll(i, d, b, f, c, a, e);
        checkAll(i, d, b, f, c, e, a);
        checkAll(i, d, b, f, e, a, c);
        checkAll(i, d, b, f, e, c, a);
        checkAll(i, d, c, a, b, e, f);
        checkAll(i, d, c, a, b, f, e);
        checkAll(i, d, c, a, e, b, f);
        checkAll(i, d, c, a, e, f, b);
        checkAll(i, d, c, a, f, b, e);
        checkAll(i, d, c, a, f, e, b);
        checkAll(i, d, c, b, a, e, f);
        checkAll(i, d, c, b, a, f, e);
        checkAll(i, d, c, b, e, a, f);
        checkAll(i, d, c, b, e, f, a);
        checkAll(i, d, c, b, f, a, e);
        checkAll(i, d, c, b, f, e, a);
        checkAll(i, d, c, e, a, b, f);
        checkAll(i, d, c, e, a, f, b);
        checkAll(i, d, c, e, b, a, f);
        checkAll(i, d, c, e, b, f, a);
        checkAll(i, d, c, e, f, a, b);
        checkAll(i, d, c, e, f, b, a);
        checkAll(i, d, c, f, a, b, e);
        checkAll(i, d, c, f, a, e, b);
        checkAll(i, d, c, f, b, a, e);
        checkAll(i, d, c, f, b, e, a);
        checkAll(i, d, c, f, e, a, b);
        checkAll(i, d, c, f, e, b, a);
        checkAll(i, d, e, a, b, c, f);
        checkAll(i, d, e, a, b, f, c);
        checkAll(i, d, e, a, c, b, f);
        checkAll(i, d, e, a, c, f, b);
        checkAll(i, d, e, a, f, b, c);
        checkAll(i, d, e, a, f, c, b);
        checkAll(i, d, e, b, a, c, f);
        checkAll(i, d, e, b, a, f, c);
        checkAll(i, d, e, b, c, a, f);
        checkAll(i, d, e, b, c, f, a);
        checkAll(i, d, e, b, f, a, c);
        checkAll(i, d, e, b, f, c, a);
        checkAll(i, d, e, c, a, b, f);
        checkAll(i, d, e, c, a, f, b);
        checkAll(i, d, e, c, b, a, f);
        checkAll(i, d, e, c, b, f, a);
        checkAll(i, d, e, c, f, a, b);
        checkAll(i, d, e, c, f, b, a);
        checkAll(i, d, e, f, a, b, c);
        checkAll(i, d, e, f, a, c, b);
        checkAll(i, d, e, f, b, a, c);
        checkAll(i, d, e, f, b, c, a);
        checkAll(i, d, e, f, c, a, b);
        checkAll(i, d, e, f, c, b, a);
        checkAll(i, d, f, a, b, c, e);
        checkAll(i, d, f, a, b, e, c);
        checkAll(i, d, f, a, c, b, e);
        checkAll(i, d, f, a, c, e, b);
        checkAll(i, d, f, a, e, b, c);
        checkAll(i, d, f, a, e, c, b);
        checkAll(i, d, f, b, a, c, e);
        checkAll(i, d, f, b, a, e, c);
        checkAll(i, d, f, b, c, a, e);
        checkAll(i, d, f, b, c, e, a);
        checkAll(i, d, f, b, e, a, c);
        checkAll(i, d, f, b, e, c, a);
        checkAll(i, d, f, c, a, b, e);
        checkAll(i, d, f, c, a, e, b);
        checkAll(i, d, f, c, b, a, e);
        checkAll(i, d, f, c, b, e, a);
        checkAll(i, d, f, c, e, a, b);
        checkAll(i, d, f, c, e, b, a);
        checkAll(i, d, f, e, a, b, c);
        checkAll(i, d, f, e, a, c, b);
        checkAll(i, d, f, e, b, a, c);
        checkAll(i, d, f, e, b, c, a);
        checkAll(i, d, f, e, c, a, b);
        checkAll(i, d, f, e, c, b, a);
        checkAll(i, e, a, b, c, d, f);
        checkAll(i, e, a, b, c, f, d);
        checkAll(i, e, a, b, d, c, f);
        checkAll(i, e, a, b, d, f, c);
        checkAll(i, e, a, b, f, c, d);
        checkAll(i, e, a, b, f, d, c);
        checkAll(i, e, a, c, b, d, f);
        checkAll(i, e, a, c, b, f, d);
        checkAll(i, e, a, c, d, b, f);
        checkAll(i, e, a, c, d, f, b);
        checkAll(i, e, a, c, f, b, d);
        checkAll(i, e, a, c, f, d, b);
        checkAll(i, e, a, d, b, c, f);
        checkAll(i, e, a, d, b, f, c);
        checkAll(i, e, a, d, c, b, f);
        checkAll(i, e, a, d, c, f, b);
        checkAll(i, e, a, d, f, b, c);
        checkAll(i, e, a, d, f, c, b);
        checkAll(i, e, a, f, b, c, d);
        checkAll(i, e, a, f, b, d, c);
        checkAll(i, e, a, f, c, b, d);
        checkAll(i, e, a, f, c, d, b);
        checkAll(i, e, a, f, d, b, c);
        checkAll(i, e, a, f, d, c, b);
        checkAll(i, e, b, a, c, d, f);
        checkAll(i, e, b, a, c, f, d);
        checkAll(i, e, b, a, d, c, f);
        checkAll(i, e, b, a, d, f, c);
        checkAll(i, e, b, a, f, c, d);
        checkAll(i, e, b, a, f, d, c);
        checkAll(i, e, b, c, a, d, f);
        checkAll(i, e, b, c, a, f, d);
        checkAll(i, e, b, c, d, a, f);
        checkAll(i, e, b, c, d, f, a);
        checkAll(i, e, b, c, f, a, d);
        checkAll(i, e, b, c, f, d, a);
        checkAll(i, e, b, d, a, c, f);
        checkAll(i, e, b, d, a, f, c);
        checkAll(i, e, b, d, c, a, f);
        checkAll(i, e, b, d, c, f, a);
        checkAll(i, e, b, d, f, a, c);
        checkAll(i, e, b, d, f, c, a);
        checkAll(i, e, b, f, a, c, d);
        checkAll(i, e, b, f, a, d, c);
        checkAll(i, e, b, f, c, a, d);
        checkAll(i, e, b, f, c, d, a);
        checkAll(i, e, b, f, d, a, c);
        checkAll(i, e, b, f, d, c, a);
        checkAll(i, e, c, a, b, d, f);
        checkAll(i, e, c, a, b, f, d);
        checkAll(i, e, c, a, d, b, f);
        checkAll(i, e, c, a, d, f, b);
        checkAll(i, e, c, a, f, b, d);
        checkAll(i, e, c, a, f, d, b);
        checkAll(i, e, c, b, a, d, f);
        checkAll(i, e, c, b, a, f, d);
        checkAll(i, e, c, b, d, a, f);
        checkAll(i, e, c, b, d, f, a);
        checkAll(i, e, c, b, f, a, d);
        checkAll(i, e, c, b, f, d, a);
        checkAll(i, e, c, d, a, b, f);
        checkAll(i, e, c, d, a, f, b);
        checkAll(i, e, c, d, b, a, f);
        checkAll(i, e, c, d, b, f, a);
        checkAll(i, e, c, d, f, a, b);
        checkAll(i, e, c, d, f, b, a);
        checkAll(i, e, c, f, a, b, d);
        checkAll(i, e, c, f, a, d, b);
        checkAll(i, e, c, f, b, a, d);
        checkAll(i, e, c, f, b, d, a);
        checkAll(i, e, c, f, d, a, b);
        checkAll(i, e, c, f, d, b, a);
        checkAll(i, e, d, a, b, c, f);
        checkAll(i, e, d, a, b, f, c);
        checkAll(i, e, d, a, c, b, f);
        checkAll(i, e, d, a, c, f, b);
        checkAll(i, e, d, a, f, b, c);
        checkAll(i, e, d, a, f, c, b);
        checkAll(i, e, d, b, a, c, f);
        checkAll(i, e, d, b, a, f, c);
        checkAll(i, e, d, b, c, a, f);
        checkAll(i, e, d, b, c, f, a);
        checkAll(i, e, d, b, f, a, c);
        checkAll(i, e, d, b, f, c, a);
        checkAll(i, e, d, c, a, b, f);
        checkAll(i, e, d, c, a, f, b);
        checkAll(i, e, d, c, b, a, f);
        checkAll(i, e, d, c, b, f, a);
        checkAll(i, e, d, c, f, a, b);
        checkAll(i, e, d, c, f, b, a);
        checkAll(i, e, d, f, a, b, c);
        checkAll(i, e, d, f, a, c, b);
        checkAll(i, e, d, f, b, a, c);
        checkAll(i, e, d, f, b, c, a);
        checkAll(i, e, d, f, c, a, b);
        checkAll(i, e, d, f, c, b, a);
        checkAll(i, e, f, a, b, c, d);
        checkAll(i, e, f, a, b, d, c);
        checkAll(i, e, f, a, c, b, d);
        checkAll(i, e, f, a, c, d, b);
        checkAll(i, e, f, a, d, b, c);
        checkAll(i, e, f, a, d, c, b);
        checkAll(i, e, f, b, a, c, d);
        checkAll(i, e, f, b, a, d, c);
        checkAll(i, e, f, b, c, a, d);
        checkAll(i, e, f, b, c, d, a);
        checkAll(i, e, f, b, d, a, c);
        checkAll(i, e, f, b, d, c, a);
        checkAll(i, e, f, c, a, b, d);
        checkAll(i, e, f, c, a, d, b);
        checkAll(i, e, f, c, b, a, d);
        checkAll(i, e, f, c, b, d, a);
        checkAll(i, e, f, c, d, a, b);
        checkAll(i, e, f, c, d, b, a);
        checkAll(i, e, f, d, a, b, c);
        checkAll(i, e, f, d, a, c, b);
        checkAll(i, e, f, d, b, a, c);
        checkAll(i, e, f, d, b, c, a);
        checkAll(i, e, f, d, c, a, b);
        checkAll(i, e, f, d, c, b, a);
        checkAll(i, f, a, b, c, d, e);
        checkAll(i, f, a, b, c, e, d);
        checkAll(i, f, a, b, d, c, e);
        checkAll(i, f, a, b, d, e, c);
        checkAll(i, f, a, b, e, c, d);
        checkAll(i, f, a, b, e, d, c);
        checkAll(i, f, a, c, b, d, e);
        checkAll(i, f, a, c, b, e, d);
        checkAll(i, f, a, c, d, b, e);
        checkAll(i, f, a, c, d, e, b);
        checkAll(i, f, a, c, e, b, d);
        checkAll(i, f, a, c, e, d, b);
        checkAll(i, f, a, d, b, c, e);
        checkAll(i, f, a, d, b, e, c);
        checkAll(i, f, a, d, c, b, e);
        checkAll(i, f, a, d, c, e, b);
        checkAll(i, f, a, d, e, b, c);
        checkAll(i, f, a, d, e, c, b);
        checkAll(i, f, a, e, b, c, d);
        checkAll(i, f, a, e, b, d, c);
        checkAll(i, f, a, e, c, b, d);
        checkAll(i, f, a, e, c, d, b);
        checkAll(i, f, a, e, d, b, c);
        checkAll(i, f, a, e, d, c, b);
        checkAll(i, f, b, a, c, d, e);
        checkAll(i, f, b, a, c, e, d);
        checkAll(i, f, b, a, d, c, e);
        checkAll(i, f, b, a, d, e, c);
        checkAll(i, f, b, a, e, c, d);
        checkAll(i, f, b, a, e, d, c);
        checkAll(i, f, b, c, a, d, e);
        checkAll(i, f, b, c, a, e, d);
        checkAll(i, f, b, c, d, a, e);
        checkAll(i, f, b, c, d, e, a);
        checkAll(i, f, b, c, e, a, d);
        checkAll(i, f, b, c, e, d, a);
        checkAll(i, f, b, d, a, c, e);
        checkAll(i, f, b, d, a, e, c);
        checkAll(i, f, b, d, c, a, e);
        checkAll(i, f, b, d, c, e, a);
        checkAll(i, f, b, d, e, a, c);
        checkAll(i, f, b, d, e, c, a);
        checkAll(i, f, b, e, a, c, d);
        checkAll(i, f, b, e, a, d, c);
        checkAll(i, f, b, e, c, a, d);
        checkAll(i, f, b, e, c, d, a);
        checkAll(i, f, b, e, d, a, c);
        checkAll(i, f, b, e, d, c, a);
        checkAll(i, f, c, a, b, d, e);
        checkAll(i, f, c, a, b, e, d);
        checkAll(i, f, c, a, d, b, e);
        checkAll(i, f, c, a, d, e, b);
        checkAll(i, f, c, a, e, b, d);
        checkAll(i, f, c, a, e, d, b);
        checkAll(i, f, c, b, a, d, e);
        checkAll(i, f, c, b, a, e, d);
        checkAll(i, f, c, b, d, a, e);
        checkAll(i, f, c, b, d, e, a);
        checkAll(i, f, c, b, e, a, d);
        checkAll(i, f, c, b, e, d, a);
        checkAll(i, f, c, d, a, b, e);
        checkAll(i, f, c, d, a, e, b);
        checkAll(i, f, c, d, b, a, e);
        checkAll(i, f, c, d, b, e, a);
        checkAll(i, f, c, d, e, a, b);
        checkAll(i, f, c, d, e, b, a);
        checkAll(i, f, c, e, a, b, d);
        checkAll(i, f, c, e, a, d, b);
        checkAll(i, f, c, e, b, a, d);
        checkAll(i, f, c, e, b, d, a);
        checkAll(i, f, c, e, d, a, b);
        checkAll(i, f, c, e, d, b, a);
        checkAll(i, f, d, a, b, c, e);
        checkAll(i, f, d, a, b, e, c);
        checkAll(i, f, d, a, c, b, e);
        checkAll(i, f, d, a, c, e, b);
        checkAll(i, f, d, a, e, b, c);
        checkAll(i, f, d, a, e, c, b);
        checkAll(i, f, d, b, a, c, e);
        checkAll(i, f, d, b, a, e, c);
        checkAll(i, f, d, b, c, a, e);
        checkAll(i, f, d, b, c, e, a);
        checkAll(i, f, d, b, e, a, c);
        checkAll(i, f, d, b, e, c, a);
        checkAll(i, f, d, c, a, b, e);
        checkAll(i, f, d, c, a, e, b);
        checkAll(i, f, d, c, b, a, e);
        checkAll(i, f, d, c, b, e, a);
        checkAll(i, f, d, c, e, a, b);
        checkAll(i, f, d, c, e, b, a);
        checkAll(i, f, d, e, a, b, c);
        checkAll(i, f, d, e, a, c, b);
        checkAll(i, f, d, e, b, a, c);
        checkAll(i, f, d, e, b, c, a);
        checkAll(i, f, d, e, c, a, b);
        checkAll(i, f, d, e, c, b, a);
        checkAll(i, f, e, a, b, c, d);
        checkAll(i, f, e, a, b, d, c);
        checkAll(i, f, e, a, c, b, d);
        checkAll(i, f, e, a, c, d, b);
        checkAll(i, f, e, a, d, b, c);
        checkAll(i, f, e, a, d, c, b);
        checkAll(i, f, e, b, a, c, d);
        checkAll(i, f, e, b, a, d, c);
        checkAll(i, f, e, b, c, a, d);
        checkAll(i, f, e, b, c, d, a);
        checkAll(i, f, e, b, d, a, c);
        checkAll(i, f, e, b, d, c, a);
        checkAll(i, f, e, c, a, b, d);
        checkAll(i, f, e, c, a, d, b);
        checkAll(i, f, e, c, b, a, d);
        checkAll(i, f, e, c, b, d, a);
        checkAll(i, f, e, c, d, a, b);
        checkAll(i, f, e, c, d, b, a);
        checkAll(i, f, e, d, a, b, c);
        checkAll(i, f, e, d, a, c, b);
        checkAll(i, f, e, d, b, a, c);
        checkAll(i, f, e, d, b, c, a);
        checkAll(i, f, e, d, c, a, b);
        checkAll(i, f, e, d, c, b, a);
    }
}

